version: "3.8"

services:
  rag_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - services:
  rag_app:
    volumes:
      - ./data:/app/data  
    restart: unless-stopped
